/**
 * Language Service
 * Handles language preference storage and retrieval
 */

import AsyncStorage from '@react-native-async-storage/async-storage';

const LANGUAGE_KEY = 'app_language';

export const LANGUAGES = {
  ENGLISH: 'English',
  HINDI: 'हिंदी',
  MARATHI: 'मराठी'
};

/**
 * Get stored language preference
 */
export const getLanguage = async () => {
  try {
    const language = await AsyncStorage.getItem(LANGUAGE_KEY);
    return language; // Return null if not set
  } catch (error) {
    console.error('Error getting language:', error);
    return null;
  }
};

/**
 * Check if language has been selected
 */
export const hasLanguageSelected = async () => {
  try {
    const language = await AsyncStorage.getItem(LANGUAGE_KEY);
    
    // Check if language exists and is valid
    let result = false;
    if (language) {
      const trimmed = language.trim();
      // Check if it's one of our valid languages (exact match)
      const validLanguages = [LANGUAGES.ENGLISH, LANGUAGES.HINDI, LANGUAGES.MARATHI];
      result = trimmed !== '' && validLanguages.some(lang => lang === trimmed);
      
      // Additional check: verify it's a valid language string
      if (result) {
        console.log('✅ Valid language found:', trimmed);
      } else {
        console.log('⚠️ Language found but not valid:', trimmed, 'Valid options:', validLanguages);
      }
    } else {
      console.log('⚠️ No language found in AsyncStorage');
    }
    
    console.log('🔍 hasLanguageSelected check:', { 
      language, 
      result,
      isValid: result,
      isNull: language === null,
      isEmpty: language === '' || language?.trim() === '',
      validLanguages: [LANGUAGES.ENGLISH, LANGUAGES.HINDI, LANGUAGES.MARATHI]
    });
    
    return result;
  } catch (error) {
    console.error('❌ Error checking language:', error);
    return false;
  }
};

/**
 * Clear language selection (for testing/reset)
 */
export const clearLanguage = async () => {
  try {
    await AsyncStorage.removeItem(LANGUAGE_KEY);
    console.log('✅ Language cleared');
    return true;
  } catch (error) {
    console.error('Error clearing language:', error);
    return false;
  }
};

/**
 * Set language preference
 */
export const setLanguage = async (language) => {
  try {
    if (!language || language.trim() === '') {
      console.error('❌ Cannot set empty language');
      return false;
    }
    
    await AsyncStorage.setItem(LANGUAGE_KEY, language);
    
    // Verify it was saved
    const verified = await AsyncStorage.getItem(LANGUAGE_KEY);
    if (verified === language) {
      console.log('✅ Language saved and verified:', language);
      return true;
    } else {
      console.error('❌ Language save verification failed:', { expected: language, got: verified });
      return false;
    }
  } catch (error) {
    console.error('❌ Error setting language:', error);
    return false;
  }
};

/**
 * Translations for different languages
 */
export const translations = {
  [LANGUAGES.ENGLISH]: {
    selectLanguage: 'Select Your Language',
    continue: 'Continue',
    login: 'Login',
    emailOrMobile: 'Email or Mobile',
    password: 'Password',
    pleaseEnterCredentials: 'Please enter login credentials',
    forgotPassword: 'Forgot your Password?',
    continueAsGuest: 'Continue as Guest (Pilgrim)',
    required: 'required',
    kumbhMela: 'Kumbh Mela',
    nashik2027: 'Mahakumbh Nashik 2027',
    divineGathering: 'Divine Gathering',
    sacredServices: 'Sacred Services',
    navigation: 'Navigation',
    medical: 'Medical',
    qrCheckin: 'QR Check-in',
    lostFound: 'Lost & Found',
    emergencyAssistance: 'Emergency Assistance',
    sos: 'SOS',
    pressHold: 'Press & Hold for 5 seconds to activate',
    keepHolding: 'Keep holding to activate SOS…',
    emergencySent: 'Emergency signal sent (demo).',
    // Common UI
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    filter: 'Filter',
    refresh: 'Refresh',
    loading: 'Loading...',
    noData: 'No data available',
    error: 'Error',
    success: 'Success',
    // Navigation
    home: 'Home',
    profile: 'Profile',
    language: 'Language',
    settings: 'Settings',
    logout: 'Logout',
    // Common actions
    view: 'View',
    details: 'Details',
    close: 'Close',
    open: 'Open',
    select: 'Select',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    // Status
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    completed: 'Completed',
    // Time
    today: 'Today',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',
    // Common messages
    noInternet: 'No internet connection',
    tryAgain: 'Try again',
    somethingWentWrong: 'Something went wrong',
    // Profile
    user: 'User',
    emailPhone: 'Email/Phone',
    role: 'Role',
    pilgrim: 'Pilgrim',
    volunteer: 'Volunteer',
    admin: 'Admin',
    medicalTeam: 'Medical Team',
    refreshProfile: 'Refresh Profile',
    signOut: 'Sign Out',
    signOutConfirm: 'Are you sure you want to sign out?',
    notSet: 'Not set',
    // Common labels
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    // Home Screen
    mahaKumbh2027: 'Maha Kumbh 2027',
    attractionsAroundNashik: 'Attractions around Nashik',
    exploreSacredPlaces: 'Explore sacred places and holy sites',
    tasteOfNashik: 'Taste of Nashik',
    discoverLocalDelicacies: 'Discover local delicacies and street food',
    divineAssistant: 'Divine Assistant',
    selectQuestionBelow: "Namaste! I'm your divine assistant. Select a question below:",
    quickQuestions: 'Quick Questions:',
    fullAssistant: 'Full Assistant',
    eatOnlyCleanStalls: 'Eat only at clean, authorized stalls near ghats',
    // Attraction Detail Screen
    attractionNotFound: 'Attraction not found',
    fromNashik: 'from Nashik',
    aboutThisPlace: 'About this Place',
    attractionDescription: '{name} is one of the most significant spiritual destinations in Nashik. This sacred site holds immense importance for devotees visiting during the Maha Kumbh Mela. Experience the divine atmosphere and connect with the rich cultural heritage of this holy place.',
    // Attractions (id 1-4: Trimbakeshwar, Ramkund, Panchvati, Saptashrungi)
    attraction1Name: 'Trimbakeshwar Temple',
    attraction1Info: 'One of the 12 Jyotirlingas, sacred Shiva temple',
    attraction1Tag: 'Jyotirlinga',
    attraction1Description: 'Trimbakeshwar Temple is one of the 12 Jyotirlingas of Lord Shiva. Located at the source of the Godavari river, it is one of the most sacred pilgrimage sites. The unique feature is the three-faced linga representing Brahma, Vishnu and Shiva.',
    attraction2Name: 'Ramkund & Godavari Ghat',
    attraction2Info: 'Sacred bathing ghat on the banks of Godavari river',
    attraction2Tag: 'Holy Dip',
    attraction2Description: 'Ramkund is the sacred bathing ghat on the banks of the Godavari river in Nashik. It is believed that Lord Rama bathed here during his exile. Millions of devotees take a holy dip here during the Kumbh Mela for spiritual purification.',
    attraction3Name: 'Panchvati',
    attraction3Info: 'Historic site from Ramayana, where Lord Rama stayed',
    attraction3Tag: 'Ramayana',
    attraction3Description: 'Panchvati is the historic site from the Ramayana where Lord Rama, Sita and Lakshmana stayed during their exile. The five banyan trees (Panch Vat) give the place its name. Key sites include Sita Gufa and Kalaram Temple.',
    attraction4Name: 'Saptashrungi Devi',
    attraction4Info: 'One of the 51 Shakti Peethas, powerful goddess temple',
    attraction4Tag: 'Shakti Peeth',
    attraction4Description: 'Saptashrungi Devi Temple is one of the 51 Shakti Peethas. The goddess is depicted with 18 arms and is believed to be self-manifested. The temple is on a hill with 510 steps. A major pilgrimage site for devotees of the Divine Mother.',
    // CM and PM Cards
    pmName: 'Shri Narendra Modi',
    pmTitle: 'Prime Minister of India',
    cmName: 'Shri Devendra Fadnavis',
    cmTitle: 'Chief Minister, Maharashtra',
    // Taste of Nashik - Food items
    food1Name: 'Misal Pav',
    food1Desc: 'Spicy local favourite for breakfast',
    food2Name: 'Kanda Poha',
    food2Desc: 'Light & filling snack near ghats',
    food3Name: 'Grapes & Juice',
    food3Desc: 'Famous Nashik vineyards & fruit',
    visitingInformation: 'Visiting Information',
    timings: 'Timings',
    open24Hours: 'Open 24 hours during Kumbh Mela',
    transport: 'Transport',
    shuttleServiceAvailable: 'Shuttle service available from main ghat',
    bestTime: 'Best Time',
    bestTimeForDarshan: 'Early morning or evening for peaceful darshan',
    // Login / Auth
    createAccount: 'Create Account',
    signUp: 'SIGN UP',
    selectYourRole: 'Select your role',
    quickLogin: 'Quick login (tap role)',
    registerAsPilgrim: 'Register as Pilgrim',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    phoneNumber: 'Phone Number',
    enterPhone: '10 digit mobile',
    emailUsername: 'Email or User ID',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter password',
    minChars: 'Min 6 chars',
    min4Characters: 'Min 4 characters',
    min6Characters: 'Min 6 characters',
    dontHaveAccount: "Don't have an account? Sign up",
    alreadyHaveAccount: 'Already have account? Login',
    welcomeBharatKumbh: 'Welcome to Bharat Kumbh App',
    loginOrSignupMessage: 'Login or sign up to access your personalized dashboard, get real-time updates, and connect with the Kumbh community. Select your role above to continue.',
    accountCreatedSuccess: 'Account created and signed in',
    signUpFailed: 'Sign up failed',
    signInFailed: 'Sign in failed',
    pleaseTryAgain: 'Please try again',
    // SOS
    sosAlertSent: 'SOS Alert Sent',
    emergencyNotified: 'Emergency services have been notified with your location!',
    failedToSendSOS: 'Failed to send SOS alert',
    cannotConnectServer: 'Cannot connect to server. Please check your connection.',
    sendingSOS: 'Sending SOS alert...',
    holdToActivate: 'HOLD FOR 5 SECONDS TO ACTIVATE',
    emergencyServicesNotified: 'Emergency services will be notified immediately',
    // Medical
    emergencyMedical: 'Emergency Medical',
    medicalRequestFillDetails: 'Fill in the details below to request medical assistance',
    patientInformation: 'Patient Information',
    enterFullNameLetters: 'Enter your full name (letters only)',
    age: 'Age',
    enterAge2Digits: 'Enter age (2 digits)',
    medicalIssue: 'Medical Issue',
    describeMedicalConcern: 'Describe your medical concern (text only)',
    knownAllergies: 'Known Allergies',
    listAllergies: 'List any allergies (if any)',
    emergencyContact: 'Emergency Contact',
    emergencyContactPlaceholder: 'Emergency contact phone number',
    submitMedicalRequest: 'Submit Medical Request',
    emergencyAlertSent: 'Emergency Alert Sent',
    medicalTeamNotified: 'Medical team has been notified and is on the way!',
    requiredFields: 'Required Fields',
    fillNameAndMedical: 'Please fill in at least Name and Medical Issue',
    medicalRequestSubmitted: 'Medical Request Submitted',
    medicalDetailsShared: 'Your details have been shared with the medical team.',
    failedToSubmitMedical: 'Failed to submit medical request',
    failedToSendEmergency: 'Failed to send emergency alert',
    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    administrationPanel: 'Administration Panel',
    dashboardOverview: 'Dashboard Overview',
    registeredPilgrims: 'Registered Pilgrims',
    totalRegistrations: 'Total Registrations',
    medicalEmergencies: 'Medical Emergencies',
    recentActivity: 'Recent Activity',
    viewAllRegistrations: 'View All Registrations',
    noRecentRegistrations: 'No recent registrations',
    quickStatistics: 'Quick Statistics',
    totalUsers: 'Total Users',
    medicalStaff: 'Medical Staff',
    resolvedSOS: 'Resolved SOS',
    administrator: 'Administrator',
    unknownDestination: 'Unknown Destination',
    groupLabel: 'Group',
    entryLabel: 'Entry',
    failedToLoadDashboard: 'Failed to load dashboard data',
    // Volunteer Dashboard
    volunteerDashboard: 'Volunteer Dashboard',
    serviceAndSupport: 'Service & Support',
    pendingSOS: 'Pending SOS',
    myTasks: 'My Tasks',
    lostFoundShort: 'Lost/Found',
    myAssignedTasks: 'My Assigned Tasks',
    noTasksAssigned: 'No tasks assigned',
    task: 'Task',
    priority: 'Priority',
    status: 'Status',
    // Medical Dashboard
    medicalDashboard: 'Medical Dashboard',
    healthAndCare: 'Health & Care',
    medicalCases: 'Medical Cases',
    filterAll: 'All',
    filterPending: 'Pending',
    filterActive: 'Active',
    filterCritical: 'Critical',
    filterHigh: 'High',
    loadingCases: 'Loading cases...',
    noCasesFound: 'No cases found',
    unknownPatient: 'Unknown Patient',
    consultation: 'Consultation',
    ageLabel: 'Age',
    failedToLoadCases: 'Failed to load medical cases',
    navigationNotAvailable: 'Navigation not available',
    // Admin sub-screens
    emergency: 'Emergency',
    filterEmergencies: 'Filter Emergencies',
    failedToLoadEmergencies: 'Failed to load emergencies',
    failedToLoadRegistrations: 'Failed to load registrations',
    registrations: 'Registrations',
    noEmergencies: 'No emergencies found',
    noRegistrations: 'No registrations found',
    caseDetails: 'Case Details',
    caseDataNotFound: 'Case data not found',
    ageNotSpecified: 'Age not specified',
    qrRegistrations: 'QR Registrations',
    filterByDestination: 'Filter by Destination',
    loadingRegistrations: 'Loading registrations...',
    loadMore: 'Load More',
    contact: 'Contact',
    reports: 'Reports',
    failedToLoadReports: 'Failed to load reports',
    failedToLoadLostFound: 'Failed to load lost & found items',
    failedToLoadSOS: 'Failed to load SOS alerts',
    // Navigation / Nearest Places
    currentLocation: 'Current Location',
    gettingYourLocation: 'Getting your location...',
    filterLocations: 'Filter Locations',
    allLocations: 'All Locations',
    ghats: 'Ghats',
    temples: 'Temples',
    camps: 'Camps',
    medicalFacilities: 'Medical Facilities',
    otherFacilities: 'Other Facilities',
    quickActions: 'Quick Actions',
    viewAllOnGoogleMaps: 'View All on Google Maps',
    showMapView: 'Show Map View',
    hideMapView: 'Hide Map View',
    nashikKumbhMelaLiveMap: 'Nashik Kumbh Mela - Live Map',
    refreshLocation: 'Refresh Location',
    navigate: 'Navigate',
    locationRequired: 'Location Required',
    pleaseWaitForLocation: 'Please wait for location to load.',
    calculating: 'Calculating...',
    couldNotOpenMaps: 'Could not open maps. Please install Google Maps.',
    nearPanchavatiRamkund: 'Near Panchavati, Ramkund Entrance',
    directRoute: 'Direct Route',
    via: 'Via',
    crowdLow: 'Low',
    crowdModerate: 'Moderate',
    crowdHigh: 'High',
    crowdVeryHigh: 'Very High',
    routeTo: 'Route to',
    distance: 'Distance',
    time: 'Time',
    crowd: 'Crowd',
    recommendedRoute: 'Recommended route (least crowded)',
    interactiveMap: 'Interactive Map',
    viewLocationsWithCrowd: 'View all {count} locations with real-time crowd data',
    openInGoogleMaps: 'Open in Google Maps',
    // Navigation - Location names & descriptions
    nav_ramkund_name: 'Ramkund',
    nav_ramkund_desc: 'Sacred bathing ghat on Godavari River',
    nav_panchavati_name: 'Panchavati Ghat',
    nav_panchavati_desc: 'Famous ghat for holy dip',
    nav_kapilatirth_name: 'Kapila Tirth',
    nav_kapilatirth_desc: 'Sacred water tank',
    nav_kalaram_name: 'Kalaram Temple',
    nav_kalaram_desc: 'Ancient black stone Ram temple',
    nav_trimbakeshwar_name: 'Trimbakeshwar Temple',
    nav_trimbakeshwar_desc: 'One of the 12 Jyotirlingas',
    nav_muktidham_name: 'Muktidham Temple',
    nav_muktidham_desc: 'White marble temple complex',
    nav_sitagufa_name: 'Sita Gufa',
    nav_sitagufa_desc: 'Cave where Sita stayed during exile',
    nav_camp1_name: 'Pilgrim Camp A',
    nav_camp1_desc: 'Main accommodation camp',
    nav_camp2_name: 'Pilgrim Camp B',
    nav_camp2_desc: 'Secondary accommodation camp',
    nav_camp3_name: 'Volunteer Camp',
    nav_camp3_desc: 'Volunteer accommodation',
    nav_medical1_name: 'Medical Tent - Ramkund',
    nav_medical1_desc: '24/7 medical assistance',
    nav_medical2_name: 'Medical Tent - Panchavati',
    nav_medical2_desc: 'Emergency medical services',
    nav_medical3_name: 'Medical Center - Main',
    nav_medical3_desc: 'Primary medical facility',
    nav_facility1_name: 'Food Court - Main',
    nav_facility1_desc: 'Main food distribution center',
    nav_facility2_name: 'Water Station A',
    nav_facility2_desc: 'Drinking water facility',
    nav_facility3_name: 'Restroom Block 1',
    nav_facility3_desc: 'Public restroom facilities',
    nav_facility4_name: 'Information Center',
    nav_facility4_desc: 'Tourist information and help desk',
    occupancyFormat: 'Occupancy',
    // QR Check-in
    scanQRCode: 'Scan QR Code',
    scanAtEntryPoints: 'Scan any QR code at entry points (Railway Station, Bus Stand, Parking Area)',
    entryPoint: 'Entry Point',
    entryPointName: 'Entry Point Name',
    enterEntryPointName: 'Enter entry point name',
    groupRegistration: 'Group Registration',
    groupSize: 'Group Size',
    groupSizePlaceholder: 'Group Size (1-50)',
    luggageCount: 'Luggage Count',
    bagsLimit: 'Bags Limit (0-20)',
    intendedDestination: 'Intended Destination',
    customDestination: 'Custom Destination',
    enterDestinationName: 'Enter destination name',
    contactInformation: 'Contact Information',
    phoneNumberRequired: 'Phone Number *',
    enterPhoneNumber: 'Enter phone number',
    contactNameOptional: 'Contact Name (Optional)',
    enterContactName: 'Enter contact name',
    groupSelfie: 'Group Selfie',
    takeGroupSelfie: 'Take Group Selfie',
    captureGroupPhoto: 'Capture group photo for identification',
    completeRegistration: 'Complete Registration',
    qrCodeScanned: 'QR Code Scanned',
    qrScannedSuccessfully: 'QR Scanned Successfully',
    qrCodeRequired: 'QR Code Required',
    pleaseScanQRFirst: 'Please scan a QR code first',
    selfieRequired: 'Selfie Required',
    pleaseTakeGroupSelfie: 'Please take a group selfie',
    invalidGroupSize: 'Invalid Group Size',
    enterValidGroupSize: 'Please enter a valid group size (1-50)',
    invalidLuggageCount: 'Invalid Luggage Count',
    enterValidLuggageCount: 'Please enter a valid luggage count',
    contactRequired: 'Contact Required',
    pleaseEnterContactPhone: 'Please enter a contact phone number',
    destinationRequired: 'Destination Required',
    pleaseEnterCustomDestination: 'Please enter a custom destination',
    registrationComplete: 'Registration Complete',
    registrationSubmittedSuccess: 'Your group registration has been submitted successfully!',
    registrationFailed: 'Registration Failed',
    cameraAccess: 'Camera Access',
    cameraAccessMessage: 'We need access to your camera to scan QR codes.',
    cameraDisabled: 'Camera access is disabled.',
    enableInSettings: 'Enable it in Settings to scan QR codes.',
    openSettings: 'Open Settings',
    scanAnyQRCode: 'Scan Any QR Code',
    alignQRInFrame: 'Align the QR code within the frame',
    railwayStation: 'Railway Station',
    busStand: 'Bus Stand',
    parkingArea: 'Parking Area',
    other: 'Other',
    // Lost & Found
    chooseOption: 'Choose an option',
    lost: 'Lost',
    found: 'Found',
    addLostDetails: 'Add Lost Details',
    addFoundDetails: 'Add Found Details',
    whatIsLost: 'What is lost?',
    whatIsFound: 'What is found?',
    whereLost: 'Where lost',
    whereFound: 'Where found',
    dateAndTime: 'Date & time',
    selectDate: 'Select date',
    selectTime: 'Select time',
    contactPhoneRequired: 'Contact Phone *',
    yourContactPhone: 'Your contact phone number',
    photos: 'Photos',
    submitLostReport: 'Submit Lost Report',
    submitFoundReport: 'Submit Found Report',
    searchLostReports: 'Search lost reports...',
    searchFoundReports: 'Search found reports...',
    recentLostReports: 'Recent Lost Reports',
    recentFoundReports: 'Recent Found Reports',
    searchResults: 'Search Results',
    loadingReports: 'Loading reports...',
    noLostReportsYet: 'No lost reports yet.',
    noFoundReportsYet: 'No found reports yet.',
    beFirstToSubmit: 'Be the first to submit one!',
    pleaseFillRequired: 'Please fill required fields',
    lostReportSubmitted: 'Lost report submitted successfully.',
    foundReportSubmitted: 'Found report submitted successfully.',
    submissionFailed: 'Submission Failed',
    failedToSubmitReport: 'Failed to submit report',
    navigationNotAvailable: 'Navigation not available. Please try again.',
    egWalletPerson: 'E.g., Wallet, Person name',
    egBagIdCard: 'E.g., Bag, ID card',
    description: 'Description',
    contactPhone: 'Contact phone',
    shortDescription: 'Short description',
    locationOrLandmark: 'Location or landmark',
    reportDetails: 'Report Details',
    noReportData: 'No report data available',
    lostItem: 'Lost Item',
    foundItem: 'Found Item',
    status: 'Status',
    itemInformation: 'Item Information',
    itemName: 'Item Name',
    type: 'Type',
    person: 'Person',
    location: 'Location',
    address: 'Address',
    coordinates: 'Coordinates',
    phone: 'Phone',
    email: 'Email',
    reportInformation: 'Report Information',
    reportedOn: 'Reported On',
    reportedBy: 'Reported By',
    user: 'User',
    unknownItem: 'Unknown Item',
    noDescription: 'No description',
    recently: 'Recently',
    justNow: 'Just now',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    yesterday: 'Yesterday',
    daysAgo: 'days ago',
    noPhoneNumber: 'No Phone Number',
    contactNotAvailable: 'Contact phone number is not available',
    unableToCall: 'Unable to make phone call',
    unableToSendSMS: 'Unable to send SMS',
    call: 'Call',
    sendSMS: 'Send SMS',
  },
  [LANGUAGES.HINDI]: {
    selectLanguage: 'अपनी भाषा चुनें',
    continue: 'जारी रखें',
    login: 'लॉगिन',
    emailOrMobile: 'ईमेल या मोबाइल',
    password: 'पासवर्ड',
    pleaseEnterCredentials: 'कृपया लॉगिन क्रेडेंशियल दर्ज करें',
    forgotPassword: 'पासवर्ड भूल गए?',
    continueAsGuest: 'अतिथि के रूप में जारी रखें (तीर्थयात्री)',
    required: 'आवश्यक',
    kumbhMela: 'कुंभ मेला',
    nashik2027: 'महाकुम्भ नासिक 2027',
    divineGathering: 'दिव्य सभा',
    sacredServices: 'पवित्र सेवाएं',
    navigation: 'नेविगेशन',
    medical: 'चिकित्सा',
    qrCheckin: 'QR चेक-इन',
    lostFound: 'खोया और मिला',
    emergencyAssistance: 'आपातकालीन सहायता',
    sos: 'SOS',
    pressHold: 'सक्रिय करने के लिए 5 सेकंड तक दबाए रखें',
    keepHolding: 'SOS सक्रिय करने के लिए दबाए रखें…',
    emergencySent: 'आपातकालीन संकेत भेजा गया (डेमो)।',
    // Common UI
    back: 'वापस',
    next: 'अगला',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    refresh: 'ताज़ा करें',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा उपलब्ध नहीं',
    error: 'त्रुटि',
    success: 'सफल',
    // Navigation
    home: 'होम',
    profile: 'प्रोफ़ाइल',
    language: 'भाषा',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',
    // Common actions
    view: 'देखें',
    details: 'विवरण',
    close: 'बंद करें',
    open: 'खोलें',
    select: 'चुनें',
    confirm: 'पुष्टि करें',
    yes: 'हाँ',
    no: 'नहीं',
    ok: 'ठीक है',
    // Status
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    pending: 'लंबित',
    completed: 'पूर्ण',
    // Time
    today: 'आज',
    yesterday: 'कल',
    tomorrow: 'कल',
    // Common messages
    noInternet: 'कोई इंटरनेट कनेक्शन नहीं',
    tryAgain: 'पुनः प्रयास करें',
    somethingWentWrong: 'कुछ गलत हो गया',
    // Profile
    user: 'उपयोगकर्ता',
    emailPhone: 'ईमेल/फोन',
    role: 'भूमिका',
    pilgrim: 'तीर्थयात्री',
    volunteer: 'स्वयंसेवक',
    admin: 'व्यवस्थापक',
    medicalTeam: 'चिकित्सा टीम',
    refreshProfile: 'प्रोफ़ाइल ताज़ा करें',
    signOut: 'साइन आउट',
    signOutConfirm: 'क्या आप वाकई साइन आउट करना चाहते हैं?',
    notSet: 'सेट नहीं',
    // Common labels
    name: 'नाम',
    email: 'ईमेल',
    phone: 'फोन',
    // Home Screen
    mahaKumbh2027: 'महा कुंभ 2027',
    attractionsAroundNashik: 'नासिक के आसपास के आकर्षण',
    exploreSacredPlaces: 'पवित्र स्थानों और पवित्र स्थलों का अन्वेषण करें',
    tasteOfNashik: 'नासिक का स्वाद',
    discoverLocalDelicacies: 'स्थानीय व्यंजन और स्ट्रीट फूड खोजें',
    divineAssistant: 'दिव्य सहायक',
    selectQuestionBelow: 'नमस्ते! मैं आपका दिव्य सहायक हूं। नीचे एक प्रश्न चुनें:',
    quickQuestions: 'त्वरित प्रश्न:',
    fullAssistant: 'पूर्ण सहायक',
    eatOnlyCleanStalls: 'केवल घाटों के पास स्वच्छ, अधिकृत स्टॉल पर खाएं',
    // Attraction Detail Screen
    attractionNotFound: 'आकर्षण नहीं मिला',
    fromNashik: 'नासिक से',
    aboutThisPlace: 'इस स्थान के बारे में',
    attractionDescription: '{name} नासिक के सबसे महत्वपूर्ण आध्यात्मिक स्थलों में से एक है। यह पवित्र स्थल महा कुंभ मेला के दौरान आने वाले भक्तों के लिए अत्यधिक महत्व रखता है। दिव्य वातावरण का अनुभव करें और इस पवित्र स्थान की समृद्ध सांस्कृतिक विरासत से जुड़ें।',
    attraction1Name: 'त्र्यंबकेश्वर मंदिर',
    attraction1Info: '12 ज्योतिर्लिंगों में से एक, पवित्र शिव मंदिर',
    attraction1Tag: 'ज्योतिर्लिंग',
    attraction1Description: 'त्र्यंबकेश्वर मंदिर भगवान शिव के 12 ज्योतिर्लिंगों में से एक है। गोदावरी नदी के उद्गम स्थल पर स्थित, यह सबसे पवित्र तीर्थ स्थलों में से एक है। तीन मुख वाले लिंग ब्रह्मा, विष्णु और शिव का प्रतिनिधित्व करते हैं।',
    attraction2Name: 'रामकुंड और गोदावरी घाट',
    attraction2Info: 'गोदावरी नदी के तट पर पवित्र स्नान घाट',
    attraction2Tag: 'पवित्र स्नान',
    attraction2Description: 'रामकुंड नासिक में गोदावरी नदी के तट पर पवित्र स्नान घाट है। माना जाता है कि भगवान राम ने वनवास के दौरान यहाँ स्नान किया था। कुंभ मेला के दौरान लाखों भक्त यहाँ पवित्र स्नान करते हैं।',
    attraction3Name: 'पंचवटी',
    attraction3Info: 'रामायण का ऐतिहासिक स्थल, जहाँ भगवान राम रुके थे',
    attraction3Tag: 'रामायण',
    attraction3Description: 'पंचवटी रामायण का ऐतिहासिक स्थल है जहाँ भगवान राम, सीता और लक्ष्मण ने वनवास के दौरान निवास किया। पाँच बरगद के पेड़ (पंच वट) ने इस स्थान को नाम दिया। सीता गुफा और कालाराम मंदिर यहाँ के प्रमुख स्थल हैं।',
    attraction4Name: 'सप्तश्रृंगी देवी',
    attraction4Info: '51 शक्ति पीठों में से एक, शक्तिशाली देवी मंदिर',
    attraction4Tag: 'शक्ति पीठ',
    attraction4Description: 'सप्तश्रृंगी देवी मंदिर 51 शक्ति पीठों में से एक है। देवी को 18 भुजाओं के साथ दर्शाया गया है और स्वयं प्रकट माना जाता है। मंदिर 510 सीढ़ियों वाली पहाड़ी पर है। दिव्य माता के भक्तों के लिए प्रमुख तीर्थ स्थल।',
    // CM and PM Cards
    pmName: 'श्री नरेंद्र मोदी',
    pmTitle: 'भारत के प्रधान मंत्री',
    cmName: 'श्री देवेंद्र फडणवीस',
    cmTitle: 'मुख्यमंत्री, महाराष्ट्र',
    // Taste of Nashik - Food items
    food1Name: 'मिसल पाव',
    food1Desc: 'नाश्ते के लिए मसालेदार स्थानीय पसंदीदा',
    food2Name: 'कांदा पोहा',
    food2Desc: 'घाटों के पास हल्का और भरपूर नाश्ता',
    food3Name: 'अंगूर और जूस',
    food3Desc: 'प्रसिद्ध नासिक अंगूर के बाग और फल',
    visitingInformation: 'यात्रा की जानकारी',
    timings: 'समय',
    open24Hours: 'कुंभ मेला के दौरान 24 घंटे खुला',
    transport: 'परिवहन',
    shuttleServiceAvailable: 'मुख्य घाट से शटल सेवा उपलब्ध',
    bestTime: 'सर्वोत्तम समय',
    bestTimeForDarshan: 'शांत दर्शन के लिए सुबह जल्दी या शाम',
    // Login / Auth
    createAccount: 'खाता बनाएं',
    signUp: 'साइन अप',
    selectYourRole: 'अपनी भूमिका चुनें',
    quickLogin: 'त्वरित लॉगिन (भूमिका टैप करें)',
    registerAsPilgrim: 'तीर्थयात्री के रूप में पंजीकरण करें',
    fullName: 'पूरा नाम',
    enterFullName: 'अपना पूरा नाम दर्ज करें',
    phoneNumber: 'फोन नंबर',
    enterPhone: '10 अंकों का मोबाइल',
    emailUsername: 'ईमेल या यूजर आईडी',
    enterEmail: 'अपना ईमेल दर्ज करें',
    enterPassword: 'पासवर्ड दर्ज करें',
    minChars: 'कम से कम 6 अक्षर',
    min4Characters: 'कम से कम 4 अक्षर',
    min6Characters: 'कम से कम 6 अक्षर',
    dontHaveAccount: 'खाता नहीं है? साइन अप करें',
    alreadyHaveAccount: 'पहले से खाता है? लॉगिन करें',
    welcomeBharatKumbh: 'भारत कुंभ ऐप में आपका स्वागत है',
    loginOrSignupMessage: 'अपने डैशबोर्ड, रियल-टाइम अपडेट और कुंभ समुदाय से जुड़ने के लिए लॉगिन या साइन अप करें। जारी रखने के लिए ऊपर अपनी भूमिका चुनें।',
    accountCreatedSuccess: 'खाता बनाया गया और साइन इन हो गया',
    signUpFailed: 'साइन अप विफल',
    signInFailed: 'साइन इन विफल',
    pleaseTryAgain: 'कृपया पुनः प्रयास करें',
    // SOS
    sosAlertSent: 'SOS अलर्ट भेजा गया',
    emergencyNotified: 'आपातकालीन सेवाओं को आपके स्थान के साथ सूचित किया गया है!',
    failedToSendSOS: 'SOS अलर्ट भेजने में विफल',
    cannotConnectServer: 'सर्वर से कनेक्ट नहीं हो सकता। कृपया अपना कनेक्शन जांचें।',
    sendingSOS: 'SOS अलर्ट भेजा जा रहा है...',
    holdToActivate: 'सक्रिय करने के लिए 5 सेकंड तक दबाए रखें',
    emergencyServicesNotified: 'आपातकालीन सेवाओं को तुरंत सूचित किया जाएगा',
    // Medical
    emergencyMedical: 'आपातकालीन चिकित्सा',
    medicalRequestFillDetails: 'चिकित्सा सहायता के लिए नीचे विवरण भरें',
    patientInformation: 'रोगी की जानकारी',
    enterFullNameLetters: 'अपना पूरा नाम दर्ज करें (केवल अक्षर)',
    age: 'उम्र',
    enterAge2Digits: 'उम्र दर्ज करें (2 अंक)',
    medicalIssue: 'चिकित्सा समस्या',
    describeMedicalConcern: 'अपनी चिकित्सा समस्या बताएं (केवल पाठ)',
    knownAllergies: 'ज्ञात एलर्जी',
    listAllergies: 'कोई एलर्जी बताएं (यदि कोई हो)',
    emergencyContact: 'आपातकालीन संपर्क',
    emergencyContactPlaceholder: 'आपातकालीन संपर्क फोन नंबर',
    submitMedicalRequest: 'चिकित्सा अनुरोध जमा करें',
    emergencyAlertSent: 'आपातकालीन अलर्ट भेजा गया',
    medicalTeamNotified: 'चिकित्सा टीम को सूचित किया गया है और रास्ते में है!',
    requiredFields: 'आवश्यक फ़ील्ड',
    fillNameAndMedical: 'कृपया कम से कम नाम और चिकित्सा समस्या भरें',
    medicalRequestSubmitted: 'चिकित्सा अनुरोध जमा कर दिया गया',
    medicalDetailsShared: 'आपकी जानकारी चिकित्सा टीम के साथ साझा की गई है।',
    failedToSubmitMedical: 'चिकित्सा अनुरोध जमा करने में विफल',
    failedToSendEmergency: 'आपातकालीन अलर्ट भेजने में विफल',
    // Admin Dashboard
    adminDashboard: 'एडमिन डैशबोर्ड',
    administrationPanel: 'प्रशासन पैनल',
    dashboardOverview: 'डैशबोर्ड अवलोकन',
    registeredPilgrims: 'पंजीकृत तीर्थयात्री',
    totalRegistrations: 'कुल पंजीकरण',
    medicalEmergencies: 'चिकित्सा आपातकाल',
    recentActivity: 'हाल की गतिविधि',
    viewAllRegistrations: 'सभी पंजीकरण देखें',
    noRecentRegistrations: 'कोई हाल का पंजीकरण नहीं',
    quickStatistics: 'त्वरित आंकड़े',
    totalUsers: 'कुल उपयोगकर्ता',
    medicalStaff: 'चिकित्सा कर्मचारी',
    resolvedSOS: 'हल किए गए SOS',
    administrator: 'व्यवस्थापक',
    unknownDestination: 'अज्ञात गंतव्य',
    groupLabel: 'समूह',
    entryLabel: 'प्रवेश',
    failedToLoadDashboard: 'डैशबोर्ड डेटा लोड करने में विफल',
    // Volunteer Dashboard
    volunteerDashboard: 'स्वयंसेवक डैशबोर्ड',
    serviceAndSupport: 'सेवा और सहायता',
    pendingSOS: 'लंबित SOS',
    myTasks: 'मेरे कार्य',
    lostFoundShort: 'खोया/मिला',
    myAssignedTasks: 'मेरे सौंपे गए कार्य',
    noTasksAssigned: 'कोई कार्य निर्दिष्ट नहीं',
    task: 'कार्य',
    priority: 'प्राथमिकता',
    status: 'स्थिति',
    // Medical Dashboard
    medicalDashboard: 'चिकित्सा डैशबोर्ड',
    healthAndCare: 'स्वास्थ्य और देखभाल',
    medicalCases: 'चिकित्सा मामले',
    filterAll: 'सभी',
    filterPending: 'लंबित',
    filterActive: 'सक्रिय',
    filterCritical: 'गंभीर',
    filterHigh: 'उच्च',
    loadingCases: 'मामले लोड हो रहे हैं...',
    noCasesFound: 'कोई मामला नहीं मिला',
    unknownPatient: 'अज्ञात रोगी',
    consultation: 'परामर्श',
    ageLabel: 'उम्र',
    failedToLoadCases: 'चिकित्सा मामले लोड करने में विफल',
    navigationNotAvailable: 'नेविगेशन उपलब्ध नहीं',
    emergency: 'आपातकाल',
    filterEmergencies: 'आपातकाल फ़िल्टर करें',
    failedToLoadEmergencies: 'आपातकाल लोड करने में विफल',
    failedToLoadRegistrations: 'पंजीकरण लोड करने में विफल',
    registrations: 'पंजीकरण',
    noEmergencies: 'कोई आपातकाल नहीं मिला',
    noRegistrations: 'कोई पंजीकरण नहीं मिला',
    caseDetails: 'मामले का विवरण',
    caseDataNotFound: 'मामले का डेटा नहीं मिला',
    ageNotSpecified: 'उम्र निर्दिष्ट नहीं',
    reports: 'रिपोर्ट',
    failedToLoadReports: 'रिपोर्ट लोड करने में विफल',
    failedToLoadLostFound: 'खोया और मिला आइटम लोड करने में विफल',
    failedToLoadSOS: 'SOS अलर्ट लोड करने में विफल',
    qrRegistrations: 'QR पंजीकरण',
    filterByDestination: 'गंतव्य के अनुसार फ़िल्टर',
    loadingRegistrations: 'पंजीकरण लोड हो रहे हैं...',
    loadMore: 'और लोड करें',
    contact: 'संपर्क',
    // Navigation / Nearest Places
    currentLocation: 'वर्तमान स्थान',
    gettingYourLocation: 'आपका स्थान लोड हो रहा है...',
    filterLocations: 'स्थान फ़िल्टर करें',
    allLocations: 'सभी स्थान',
    ghats: 'घाट',
    temples: 'मंदिर',
    camps: 'कैंप',
    medicalFacilities: 'चिकित्सा सुविधाएं',
    otherFacilities: 'अन्य सुविधाएं',
    quickActions: 'त्वरित क्रियाएं',
    viewAllOnGoogleMaps: 'गूगल मैप्स पर सभी देखें',
    showMapView: 'मैप दृश्य दिखाएं',
    hideMapView: 'मैप छिपाएं',
    nashikKumbhMelaLiveMap: 'नासिक कुंभ मेला - लाइव मैप',
    refreshLocation: 'स्थान रिफ्रेश करें',
    navigate: 'नेविगेट',
    locationRequired: 'स्थान आवश्यक',
    pleaseWaitForLocation: 'कृपया स्थान लोड होने की प्रतीक्षा करें।',
    calculating: 'गणना हो रही है...',
    couldNotOpenMaps: 'मैप खोल नहीं सके। कृपया गूगल मैप्स इंस्टॉल करें।',
    nearPanchavatiRamkund: 'पंचवटी, रामकुंड प्रवेश के पास',
    directRoute: 'सीधा मार्ग',
    via: 'के माध्यम से',
    crowdLow: 'कम',
    crowdModerate: 'मध्यम',
    crowdHigh: 'अधिक',
    crowdVeryHigh: 'बहुत अधिक',
    routeTo: 'मार्ग',
    distance: 'दूरी',
    time: 'समय',
    crowd: 'भीड़',
    recommendedRoute: 'अनुशंसित मार्ग (कम भीड़)',
    interactiveMap: 'इंटरैक्टिव मैप',
    viewLocationsWithCrowd: '{count} स्थान रियल-टाइम भीड़ डेटा के साथ देखें',
    openInGoogleMaps: 'गूगल मैप्स में खोलें',
    nav_ramkund_name: 'रामकुंड',
    nav_ramkund_desc: 'गोदावरी नदी पर पवित्र स्नान घाट',
    nav_panchavati_name: 'पंचवटी घाट',
    nav_panchavati_desc: 'पवित्र स्नान के लिए प्रसिद्ध घाट',
    nav_kapilatirth_name: 'कपिला तीर्थ',
    nav_kapilatirth_desc: 'पवित्र जल कुंड',
    nav_kalaram_name: 'कालाराम मंदिर',
    nav_kalaram_desc: 'प्राचीन काला पत्थर राम मंदिर',
    nav_trimbakeshwar_name: 'त्र्यंबकेश्वर मंदिर',
    nav_trimbakeshwar_desc: '12 ज्योतिर्लिंगों में से एक',
    nav_muktidham_name: 'मुक्तिधाम मंदिर',
    nav_muktidham_desc: 'सफेद संगमरमर मंदिर परिसर',
    nav_sitagufa_name: 'सीता गुफा',
    nav_sitagufa_desc: 'वनवास के दौरान सीता का निवास स्थान',
    nav_camp1_name: 'तीर्थयात्री कैंप ए',
    nav_camp1_desc: 'मुख्य आवास कैंप',
    nav_camp2_name: 'तीर्थयात्री कैंप बी',
    nav_camp2_desc: 'द्वितीयक आवास कैंप',
    nav_camp3_name: 'स्वयंसेवक कैंप',
    nav_camp3_desc: 'स्वयंसेवक आवास',
    nav_medical1_name: 'चिकित्सा टेंट - रामकुंड',
    nav_medical1_desc: '24/7 चिकित्सा सहायता',
    nav_medical2_name: 'चिकित्सा टेंट - पंचवटी',
    nav_medical2_desc: 'आपातकालीन चिकित्सा सेवाएं',
    nav_medical3_name: 'चिकित्सा केंद्र - मुख्य',
    nav_medical3_desc: 'प्राथमिक चिकित्सा सुविधा',
    nav_facility1_name: 'फूड कोर्ट - मुख्य',
    nav_facility1_desc: 'मुख्य भोजन वितरण केंद्र',
    nav_facility2_name: 'वाटर स्टेशन ए',
    nav_facility2_desc: 'पीने का पानी सुविधा',
    nav_facility3_name: 'शौचालय ब्लॉक 1',
    nav_facility3_desc: 'सार्वजनिक शौचालय सुविधाएं',
    nav_facility4_name: 'सूचना केंद्र',
    nav_facility4_desc: 'पर्यटक जानकारी और हेल्प डेस्क',
    occupancyFormat: 'अधिभोग',
    // QR Check-in
    scanQRCode: 'QR कोड स्कैन करें',
    scanAtEntryPoints: 'प्रवेश बिंदुओं पर कोई QR कोड स्कैन करें (रेलवे स्टेशन, बस स्टैंड, पार्किंग)',
    entryPoint: 'प्रवेश बिंदु',
    entryPointName: 'प्रवेश बिंदु का नाम',
    enterEntryPointName: 'प्रवेश बिंदु का नाम दर्ज करें',
    groupRegistration: 'समूह पंजीकरण',
    groupSize: 'समूह का आकार',
    groupSizePlaceholder: 'समूह का आकार (1-50)',
    luggageCount: 'सामान की संख्या',
    bagsLimit: 'बैग सीमा (0-20)',
    intendedDestination: 'गंतव्य स्थान',
    customDestination: 'कस्टम गंतव्य',
    enterDestinationName: 'गंतव्य का नाम दर्ज करें',
    contactInformation: 'संपर्क जानकारी',
    phoneNumberRequired: 'फोन नंबर *',
    enterPhoneNumber: 'फोन नंबर दर्ज करें',
    contactNameOptional: 'संपर्क नाम (वैकल्पिक)',
    enterContactName: 'संपर्क नाम दर्ज करें',
    groupSelfie: 'समूह सेल्फी',
    takeGroupSelfie: 'समूह सेल्फी लें',
    captureGroupPhoto: 'पहचान के लिए समूह फोटो कैप्चर करें',
    completeRegistration: 'पंजीकरण पूर्ण करें',
    qrCodeScanned: 'QR कोड स्कैन हो गया',
    qrScannedSuccessfully: 'QR सफलतापूर्वक स्कैन हुआ',
    qrCodeRequired: 'QR कोड आवश्यक',
    pleaseScanQRFirst: 'कृपया पहले QR कोड स्कैन करें',
    selfieRequired: 'सेल्फी आवश्यक',
    pleaseTakeGroupSelfie: 'कृपया समूह सेल्फी लें',
    invalidGroupSize: 'अमान्य समूह आकार',
    enterValidGroupSize: 'कृपया मान्य समूह आकार दर्ज करें (1-50)',
    invalidLuggageCount: 'अमान्य सामान संख्या',
    enterValidLuggageCount: 'कृपया मान्य सामान संख्या दर्ज करें',
    contactRequired: 'संपर्क आवश्यक',
    pleaseEnterContactPhone: 'कृपया संपर्क फोन नंबर दर्ज करें',
    destinationRequired: 'गंतव्य आवश्यक',
    pleaseEnterCustomDestination: 'कृपया कस्टम गंतव्य दर्ज करें',
    registrationComplete: 'पंजीकरण पूर्ण',
    registrationSubmittedSuccess: 'आपका समूह पंजीकरण सफलतापूर्वक जमा हो गया!',
    registrationFailed: 'पंजीकरण विफल',
    cameraAccess: 'कैमरा एक्सेस',
    cameraAccessMessage: 'QR कोड स्कैन करने के लिए हमें आपके कैमरे की आवश्यकता है।',
    cameraDisabled: 'कैमरा एक्सेस अक्षम है।',
    enableInSettings: 'QR स्कैन करने के लिए सेटिंग्स में सक्षम करें।',
    openSettings: 'सेटिंग्स खोलें',
    scanAnyQRCode: 'कोई QR कोड स्कैन करें',
    alignQRInFrame: 'QR कोड को फ्रेम में संरेखित करें',
    railwayStation: 'रेलवे स्टेशन',
    busStand: 'बस स्टैंड',
    parkingArea: 'पार्किंग क्षेत्र',
    other: 'अन्य',
    // Lost & Found
    chooseOption: 'एक विकल्प चुनें',
    lost: 'खोया',
    found: 'मिला',
    addLostDetails: 'खोया विवरण जोड़ें',
    addFoundDetails: 'मिला विवरण जोड़ें',
    whatIsLost: 'क्या खोया?',
    whatIsFound: 'क्या मिला?',
    whereLost: 'कहाँ खोया',
    whereFound: 'कहाँ मिला',
    dateAndTime: 'तारीख और समय',
    selectDate: 'तारीख चुनें',
    selectTime: 'समय चुनें',
    contactPhoneRequired: 'संपर्क फोन *',
    yourContactPhone: 'आपका संपर्क फोन नंबर',
    photos: 'फोटो',
    submitLostReport: 'खोया रिपोर्ट जमा करें',
    submitFoundReport: 'मिला रिपोर्ट जमा करें',
    searchLostReports: 'खोया रिपोर्ट खोजें...',
    searchFoundReports: 'मिला रिपोर्ट खोजें...',
    recentLostReports: 'हाल की खोया रिपोर्ट',
    recentFoundReports: 'हाल की मिला रिपोर्ट',
    searchResults: 'खोज परिणाम',
    loadingReports: 'रिपोर्ट लोड हो रही हैं...',
    noLostReportsYet: 'अभी तक कोई खोया रिपोर्ट नहीं।',
    noFoundReportsYet: 'अभी तक कोई मिला रिपोर्ट नहीं।',
    beFirstToSubmit: 'पहले जमा करने वाले बनें!',
    pleaseFillRequired: 'कृपया आवश्यक फ़ील्ड भरें',
    lostReportSubmitted: 'खोया रिपोर्ट सफलतापूर्वक जमा हो गई।',
    foundReportSubmitted: 'मिला रिपोर्ट सफलतापूर्वक जमा हो गई।',
    submissionFailed: 'जमा करने में विफल',
    failedToSubmitReport: 'रिपोर्ट जमा करने में विफल',
    navigationNotAvailable: 'नेविगेशन उपलब्ध नहीं। कृपया पुनः प्रयास करें।',
    egWalletPerson: 'जैसे, बटुआ, व्यक्ति का नाम',
    egBagIdCard: 'जैसे, बैग, आईडी कार्ड',
    description: 'विवरण',
    contactPhone: 'संपर्क फोन',
    shortDescription: 'संक्षिप्त विवरण',
    locationOrLandmark: 'स्थान या लैंडमार्क',
    reportDetails: 'रिपोर्ट विवरण',
    noReportData: 'कोई रिपोर्ट डेटा उपलब्ध नहीं',
    lostItem: 'खोया आइटम',
    foundItem: 'मिला आइटम',
    status: 'स्थिति',
    itemInformation: 'आइटम जानकारी',
    itemName: 'आइटम का नाम',
    type: 'प्रकार',
    person: 'व्यक्ति',
    location: 'स्थान',
    address: 'पता',
    coordinates: 'निर्देशांक',
    phone: 'फोन',
    email: 'ईमेल',
    reportInformation: 'रिपोर्ट जानकारी',
    reportedOn: 'रिपोर्ट की तारीख',
    reportedBy: 'रिपोर्ट किया',
    user: 'उपयोगकर्ता',
    unknownItem: 'अज्ञात आइटम',
    noDescription: 'कोई विवरण नहीं',
    recently: 'हाल ही में',
    justNow: 'अभी',
    minutesAgo: 'मिनट पहले',
    hoursAgo: 'घंटे पहले',
    yesterday: 'कल',
    daysAgo: 'दिन पहले',
    noPhoneNumber: 'कोई फोन नंबर नहीं',
    contactNotAvailable: 'संपर्क फोन नंबर उपलब्ध नहीं',
    unableToCall: 'फोन कॉल करने में असमर्थ',
    unableToSendSMS: 'SMS भेजने में असमर्थ',
    call: 'कॉल करें',
    sendSMS: 'SMS भेजें',
  },
  [LANGUAGES.MARATHI]: {
    selectLanguage: 'तुमची भाषा निवडा',
    continue: 'सुरू ठेवा',
    login: 'लॉगिन',
    emailOrMobile: 'ईमेल किंवा मोबाइल',
    password: 'पासवर्ड',
    pleaseEnterCredentials: 'कृपया लॉगिन क्रेडेंशियल प्रविष्ट करा',
    forgotPassword: 'पासवर्ड विसरलात?',
    continueAsGuest: 'अतिथी म्हणून सुरू ठेवा (तीर्थयात्री)',
    required: 'आवश्यक',
    kumbhMela: 'कुंभ मेळा',
    nashik2027: 'महाकुम्भ नाशिक 2027',
    divineGathering: 'दिव्य सभा',
    sacredServices: 'पवित्र सेवा',
    navigation: 'नेव्हिगेशन',
    medical: 'वैद्यकीय',
    qrCheckin: 'QR चेक-इन',
    lostFound: 'हरवले आणि सापडले',
    emergencyAssistance: 'आपत्कालीन मदत',
    sos: 'SOS',
    pressHold: 'सक्रिय करण्यासाठी 5 सेकंद दाबून ठेवा',
    keepHolding: 'SOS सक्रिय करण्यासाठी दाबून ठेवा…',
    emergencySent: 'आपत्कालीन सिग्नल पाठवला (डेमो)।',
    // Common UI
    back: 'मागे',
    next: 'पुढे',
    submit: 'सबमिट करा',
    cancel: 'रद्द करा',
    save: 'जतन करा',
    delete: 'हटवा',
    edit: 'संपादन करा',
    search: 'शोधा',
    filter: 'फिल्टर',
    refresh: 'रिफ्रेश करा',
    loading: 'लोड होत आहे...',
    noData: 'डेटा उपलब्ध नाही',
    error: 'त्रुटी',
    success: 'यशस्वी',
    // Navigation
    home: 'होम',
    profile: 'प्रोफाइल',
    language: 'भाषा',
    settings: 'सेटिंग्ज',
    logout: 'लॉगआउट',
    // Common actions
    view: 'पहा',
    details: 'तपशील',
    close: 'बंद करा',
    open: 'उघडा',
    select: 'निवडा',
    confirm: 'पुष्टी करा',
    yes: 'होय',
    no: 'नाही',
    ok: 'ठीक आहे',
    // Status
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    pending: 'प्रलंबित',
    completed: 'पूर्ण',
    // Time
    today: 'आज',
    yesterday: 'काल',
    tomorrow: 'उद्या',
    // Common messages
    noInternet: 'इंटरनेट कनेक्शन नाही',
    tryAgain: 'पुन्हा प्रयत्न करा',
    somethingWentWrong: 'काहीतरी चुकीचे झाले',
    // Profile
    user: 'वापरकर्ता',
    emailPhone: 'ईमेल/फोन',
    role: 'भूमिका',
    pilgrim: 'तीर्थयात्री',
    volunteer: 'स्वयंसेवक',
    admin: 'प्रशासक',
    medicalTeam: 'वैद्यकीय संघ',
    refreshProfile: 'प्रोफाइल रिफ्रेश करा',
    signOut: 'साइन आउट',
    signOutConfirm: 'तुम्हाला खरोखर साइन आउट करायचे आहे?',
    notSet: 'सेट नाही',
    // Common labels
    name: 'नाव',
    email: 'ईमेल',
    phone: 'फोन',
    // Home Screen
    mahaKumbh2027: 'महा कुंभ 2027',
    attractionsAroundNashik: 'नाशिकच्या आसपासचे आकर्षण',
    exploreSacredPlaces: 'पवित्र ठिकाणे आणि पवित्र स्थळे एक्सप्लोर करा',
    tasteOfNashik: 'नाशिकचा चव',
    discoverLocalDelicacies: 'स्थानिक व्यंजने आणि स्ट्रीट फूड शोधा',
    divineAssistant: 'दिव्य सहाय्यक',
    selectQuestionBelow: 'नमस्कार! मी तुमचा दिव्य सहाय्यक आहे. खाली एक प्रश्न निवडा:',
    quickQuestions: 'त्वरित प्रश्न:',
    fullAssistant: 'पूर्ण सहाय्यक',
    eatOnlyCleanStalls: 'फक्त घाटांजवळ स्वच्छ, अधिकृत स्टॉलवर खा',
    // Attraction Detail (Marathi - reuse from English block if missing)
    attractionNotFound: 'आकर्षण सापडले नाही',
    fromNashik: 'नाशिक पासून',
    aboutThisPlace: 'या ठिकाणाबद्दल',
    visitingInformation: 'भेटीची माहिती',
    timings: 'वेळ',
    open24Hours: 'कुंभ मेळा दरम्यान 24 तास खुले',
    transport: 'वाहतूक',
    shuttleServiceAvailable: 'मुख्य घाटावरून शटल सेवा उपलब्ध',
    bestTime: 'सर्वोत्तम वेळ',
    bestTimeForDarshan: 'शांत दर्शनासाठी सकाळी लवकर किंवा संध्याकाळी',
    attractionDescription: '{name} नाशिकमधील सर्वात महत्त्वाच्या आध्यात्मिक ठिकाणांपैकी एक आहे.',
    attraction1Name: 'त्र्यंबकेश्वर मंदिर',
    attraction1Info: '12 ज्योतिर्लिंगांपैकी एक, पवित्र शिव मंदिर',
    attraction1Tag: 'ज्योतिर्लिंग',
    attraction1Description: 'त्र्यंबकेश्वर मंदिर भगवान शिवाच्या 12 ज्योतिर्लिंगांपैकी एक आहे. गोदावरी नदीच्या उगमस्थानावर असलेले, हे सर्वात पवित्र तीर्थस्थळ आहे. तीन मुख असलेले लिंग ब्रह्मा, विष्णू आणि शिवाचे प्रतिनिधित्व करते.',
    attraction2Name: 'रामकुंड आणि गोदावरी घाट',
    attraction2Info: 'गोदावरी नदीच्या काठावरील पवित्र स्नान घाट',
    attraction2Tag: 'पवित्र स्नान',
    attraction2Description: 'रामकुंड नाशिकमधील गोदावरी नदीच्या काठावरील पवित्र स्नान घाट आहे. भगवान रामाने वनवासादरम्यान येथे स्नान केले असे मानले जाते. कुंभ मेला दरम्यान लाखो भक्त येथे पवित्र स्नान करतात.',
    attraction3Name: 'पंचवटी',
    attraction3Info: 'रामायणातील ऐतिहासिक ठिकाण, जेथे भगवान राम राहिले',
    attraction3Tag: 'रामायण',
    attraction3Description: 'पंचवटी रामायणातील ऐतिहासिक ठिकाण आहे जेथे भगवान राम, सीता आणि लक्ष्मण वनवासादरम्यान राहिले. पाच वटवृक्षांनी (पंच वट) या ठिकाणाला नाव दिले. सीता गुफा आणि कालाराम मंदिर येथील प्रमुख ठिकाणे आहेत.',
    attraction4Name: 'सप्तश्रृंगी देवी',
    attraction4Info: '51 शक्ती पीठांपैकी एक, शक्तिशाली देवी मंदिर',
    attraction4Tag: 'शक्ती पीठ',
    attraction4Description: 'सप्तश्रृंगी देवी मंदिर 51 शक्ती पीठांपैकी एक आहे. देवी अठरा हातांसह चित्रित आहे आणि स्वयंभू मानली जाते. मंदिर 510 पायऱ्यांच्या टेकडीवर आहे. दिव्य मातेच्या भक्तांचे प्रमुख तीर्थस्थळ.',
    // CM and PM Cards
    pmName: 'श्री नरेंद्र मोदी',
    pmTitle: 'भारताचे पंतप्रधान',
    cmName: 'श्री देवेंद्र फडणवीस',
    cmTitle: 'मुख्यमंत्री, महाराष्ट्र',
    // Taste of Nashik - Food items
    food1Name: 'मिसळ पाव',
    food1Desc: 'नाश्त्यासाठी मसालेदार स्थानिक आवड',
    food2Name: 'कांदा पोहे',
    food2Desc: 'घाटांजवळ हलके आणि पोटभर नाश्ता',
    food3Name: 'द्राक्षे आणि रस',
    food3Desc: 'प्रसिद्ध नाशिक द्राक्षवन आणि फळे',
    // Login / Auth
    createAccount: 'खाते तयार करा',
    signUp: 'साइन अप',
    selectYourRole: 'तुमची भूमिका निवडा',
    quickLogin: 'जलद लॉगिन (भूमिका टॅप करा)',
    registerAsPilgrim: 'तीर्थयात्री म्हणून नोंदणी करा',
    fullName: 'पूर्ण नाव',
    enterFullName: 'तुमचे पूर्ण नाव प्रविष्ट करा',
    phoneNumber: 'फोन नंबर',
    enterPhone: '10 अंकी मोबाइल',
    emailUsername: 'ईमेल किंवा युजर आयडी',
    enterEmail: 'तुमचा ईमेल प्रविष्ट करा',
    enterPassword: 'पासवर्ड प्रविष्ट करा',
    minChars: 'किमान 6 अक्षरे',
    min4Characters: 'किमान 4 अक्षरे',
    min6Characters: 'किमान 6 अक्षरे',
    dontHaveAccount: 'खाते नाही? साइन अप करा',
    alreadyHaveAccount: 'आधीच खाते आहे? लॉगिन करा',
    welcomeBharatKumbh: 'भारत कुंभ अॅपमध्ये आपले स्वागत आहे',
    loginOrSignupMessage: 'तुमचे डॅशबोर्ड, रिअल-टाइम अपडेट्स आणि कुंभ समुदायाशी जोडण्यासाठी लॉगिन किंवा साइन अप करा. सुरू ठेवण्यासाठी वरील भूमिका निवडा.',
    accountCreatedSuccess: 'खाते तयार झाले आणि साइन इन झाले',
    signUpFailed: 'साइन अप अयशस्वी',
    signInFailed: 'साइन इन अयशस्वी',
    pleaseTryAgain: 'कृपया पुन्हा प्रयत्न करा',
    // SOS
    sosAlertSent: 'SOS अलर्ट पाठवला',
    emergencyNotified: 'आपत्कालीन सेवांना तुमच्या स्थानासह सूचित केले आहे!',
    failedToSendSOS: 'SOS अलर्ट पाठवण्यात अयशस्वी',
    cannotConnectServer: 'सर्वरशी कनेक्ट होऊ शकत नाही. कृपया तुमचे कनेक्शन तपासा.',
    sendingSOS: 'SOS अलर्ट पाठवला जात आहे...',
    holdToActivate: 'सक्रिय करण्यासाठी 5 सेकंद दाबून ठेवा',
    emergencyServicesNotified: 'आपत्कालीन सेवांना त्वरित सूचित केले जाईल',
    // Medical
    emergencyMedical: 'आपत्कालीन वैद्यकीय',
    medicalRequestFillDetails: 'वैद्यकीय मदत मागण्यासाठी खाली तपशील भरा',
    patientInformation: 'रुग्णाची माहिती',
    enterFullNameLetters: 'तुमचे पूर्ण नाव प्रविष्ट करा (फक्त अक्षरे)',
    age: 'वय',
    enterAge2Digits: 'वय प्रविष्ट करा (2 अंक)',
    medicalIssue: 'वैद्यकीय समस्या',
    describeMedicalConcern: 'तुमची वैद्यकीय समस्या वर्णन करा (फक्त मजकूर)',
    knownAllergies: 'ज्ञात अॅलर्जी',
    listAllergies: 'कोणतीही अॅलर्जी सूचीबद्ध करा (असल्यास)',
    emergencyContact: 'आपत्कालीन संपर्क',
    emergencyContactPlaceholder: 'आपत्कालीन संपर्क फोन नंबर',
    submitMedicalRequest: 'वैद्यकीय विनंती सबमिट करा',
    emergencyAlertSent: 'आपत्कालीन अलर्ट पाठवला',
    medicalTeamNotified: 'वैद्यकीय टीमला सूचित केले आहे आणि मार्गावर आहे!',
    requiredFields: 'आवश्यक फील्ड',
    fillNameAndMedical: 'कृपया किमान नाव आणि वैद्यकीय समस्या भरा',
    medicalRequestSubmitted: 'वैद्यकीय विनंती सबमिट करण्यात आली',
    medicalDetailsShared: 'तुमचे तपशील वैद्यकीय टीमसोबत सामायिक केले आहेत.',
    failedToSubmitMedical: 'वैद्यकीय विनंती सबमिट करण्यात अयशस्वी',
    failedToSendEmergency: 'आपत्कालीन अलर्ट पाठवण्यात अयशस्वी',
    // Admin Dashboard
    adminDashboard: 'प्रशासक डॅशबोर्ड',
    administrationPanel: 'प्रशासन पॅनेल',
    dashboardOverview: 'डॅशबोर्ड विहंगावलोकन',
    registeredPilgrims: 'नोंदणीकृत तीर्थयात्री',
    totalRegistrations: 'एकूण नोंदणी',
    medicalEmergencies: 'वैद्यकीय आपत्काल',
    recentActivity: 'अलीकडील क्रियाकलाप',
    viewAllRegistrations: 'सर्व नोंदणी पहा',
    noRecentRegistrations: 'अलीकडील नोंदणी नाहीत',
    quickStatistics: 'त्वरित आकडेवारी',
    totalUsers: 'एकूण वापरकर्ते',
    medicalStaff: 'वैद्यकीय कर्मचारी',
    resolvedSOS: 'सोडवलेले SOS',
    administrator: 'प्रशासक',
    unknownDestination: 'अज्ञात गंतव्य',
    groupLabel: 'गट',
    entryLabel: 'प्रवेश',
    failedToLoadDashboard: 'डॅशबोर्ड डेटा लोड करण्यात अयशस्वी',
    // Volunteer Dashboard
    volunteerDashboard: 'स्वयंसेवक डॅशबोर्ड',
    serviceAndSupport: 'सेवा आणि समर्थन',
    pendingSOS: 'प्रलंबित SOS',
    myTasks: 'माझी कार्ये',
    lostFoundShort: 'हरवले/सापडले',
    myAssignedTasks: 'माझी नियुक्त कार्ये',
    noTasksAssigned: 'कार्य नियुक्त नाही',
    task: 'कार्य',
    priority: 'प्राधान्य',
    status: 'स्थिती',
    // Medical Dashboard
    medicalDashboard: 'वैद्यकीय डॅशबोर्ड',
    healthAndCare: 'आरोग्य आणि काळजी',
    medicalCases: 'वैद्यकीय प्रकरणे',
    filterAll: 'सर्व',
    filterPending: 'प्रलंबित',
    filterActive: 'सक्रिय',
    filterCritical: 'गंभीर',
    filterHigh: 'जास्त',
    loadingCases: 'प्रकरणे लोड होत आहेत...',
    noCasesFound: 'प्रकरण सापडले नाही',
    unknownPatient: 'अज्ञात रुग्ण',
    consultation: 'सल्लामसलत',
    ageLabel: 'वय',
    failedToLoadCases: 'वैद्यकीय प्रकरणे लोड करण्यात अयशस्वी',
    navigationNotAvailable: 'नेव्हिगेशन उपलब्ध नाही',
    emergency: 'आपत्काल',
    filterEmergencies: 'आपत्काल फिल्टर करा',
    failedToLoadEmergencies: 'आपत्काल लोड करण्यात अयशस्वी',
    failedToLoadRegistrations: 'नोंदणी लोड करण्यात अयशस्वी',
    registrations: 'नोंदणी',
    noEmergencies: 'आपत्काल सापडले नाहीत',
    noRegistrations: 'नोंदणी सापडली नाही',
    caseDetails: 'प्रकरण तपशील',
    caseDataNotFound: 'प्रकरण डेटा सापडला नाही',
    ageNotSpecified: 'वय निर्दिष्ट नाही',
    reports: 'अहवाल',
    failedToLoadReports: 'अहवाल लोड करण्यात अयशस्वी',
    failedToLoadLostFound: 'हरवले आणि सापडले आयटम लोड करण्यात अयशस्वी',
    failedToLoadSOS: 'SOS अलर्ट लोड करण्यात अयशस्वी',
    qrRegistrations: 'QR नोंदणी',
    filterByDestination: 'गंतव्यानुसार फिल्टर',
    loadingRegistrations: 'नोंदणी लोड होत आहेत...',
    loadMore: 'अधिक लोड करा',
    contact: 'संपर्क',
    // Navigation / Nearest Places
    currentLocation: 'वर्तमान स्थान',
    gettingYourLocation: 'तुमचे स्थान लोड होत आहे...',
    filterLocations: 'स्थान फिल्टर करा',
    allLocations: 'सर्व स्थाने',
    ghats: 'घाट',
    temples: 'मंदिरे',
    camps: 'कॅम्प',
    medicalFacilities: 'वैद्यकीय सुविधा',
    otherFacilities: 'इतर सुविधा',
    quickActions: 'त्वरित क्रिया',
    viewAllOnGoogleMaps: 'गूगल मॅप्सवर सर्व पहा',
    showMapView: 'मॅप दृश्य दाखवा',
    hideMapView: 'मॅप लपवा',
    nashikKumbhMelaLiveMap: 'नाशिक कुंभ मेळा - लाइव्ह मॅप',
    refreshLocation: 'स्थान रिफ्रेश करा',
    navigate: 'नेव्हिगेट',
    locationRequired: 'स्थान आवश्यक',
    pleaseWaitForLocation: 'कृपया स्थान लोड होण्याची प्रतीक्षा करा.',
    calculating: 'गणना होत आहे...',
    couldNotOpenMaps: 'मॅप उघडू शकले नाही. कृपया गूगल मॅप्स इंस्टॉल करा.',
    nearPanchavatiRamkund: 'पंचवटी, रामकुंड प्रवेशाजवळ',
    directRoute: 'थेट मार्ग',
    via: 'मार्फत',
    crowdLow: 'कमी',
    crowdModerate: 'मध्यम',
    crowdHigh: 'जास्त',
    crowdVeryHigh: 'खूप जास्त',
    routeTo: 'मार्ग',
    distance: 'अंतर',
    time: 'वेळ',
    crowd: 'गर्दी',
    recommendedRoute: 'शिफारसीत मार्ग (कमी गर्दी)',
    interactiveMap: 'इंटरॅक्टिव नकाशा',
    viewLocationsWithCrowd: '{count} ठिकाणे रिअल-टाइम गर्दी डेटासह पहा',
    openInGoogleMaps: 'गूगल मॅप्समध्ये उघडा',
    nav_ramkund_name: 'रामकुंड',
    nav_ramkund_desc: 'गोदावरी नदीवरील पवित्र स्नान घाट',
    nav_panchavati_name: 'पंचवटी घाट',
    nav_panchavati_desc: 'पवित्र स्नानासाठी प्रसिद्ध घाट',
    nav_kapilatirth_name: 'कपिला तीर्थ',
    nav_kapilatirth_desc: 'पवित्र जल कुंड',
    nav_kalaram_name: 'कालाराम मंदिर',
    nav_kalaram_desc: 'प्राचीन काळा दगड राम मंदिर',
    nav_trimbakeshwar_name: 'त्र्यंबकेश्वर मंदिर',
    nav_trimbakeshwar_desc: '12 ज्योतिर्लिंगांपैकी एक',
    nav_muktidham_name: 'मुक्तिधाम मंदिर',
    nav_muktidham_desc: 'पांढरा संगमरवरी मंदिर परिसर',
    nav_sitagufa_name: 'सीता गुफा',
    nav_sitagufa_desc: 'वनवासादरम्यान सीतेचे निवासस्थान',
    nav_camp1_name: 'तीर्थयात्री कॅम्प अ',
    nav_camp1_desc: 'मुख्य निवास कॅम्प',
    nav_camp2_name: 'तीर्थयात्री कॅम्प ब',
    nav_camp2_desc: 'दुय्यम निवास कॅम्प',
    nav_camp3_name: 'स्वयंसेवक कॅम्प',
    nav_camp3_desc: 'स्वयंसेवक निवास',
    nav_medical1_name: 'वैद्यकीय टेंट - रामकुंड',
    nav_medical1_desc: '24/7 वैद्यकीय मदत',
    nav_medical2_name: 'वैद्यकीय टेंट - पंचवटी',
    nav_medical2_desc: 'आपत्कालीन वैद्यकीय सेवा',
    nav_medical3_name: 'वैद्यकीय केंद्र - मुख्य',
    nav_medical3_desc: 'प्राथमिक वैद्यकीय सुविधा',
    nav_facility1_name: 'फूड कोर्ट - मुख्य',
    nav_facility1_desc: 'मुख्य अन्न वितरण केंद्र',
    nav_facility2_name: 'वॉटर स्टेशन अ',
    nav_facility2_desc: 'पिण्याचे पाणी सुविधा',
    nav_facility3_name: 'शौचालय ब्लॉक 1',
    nav_facility3_desc: 'सार्वजनिक शौचालय सुविधा',
    nav_facility4_name: 'माहिती केंद्र',
    nav_facility4_desc: 'पर्यटक माहिती आणि मदत डेस्क',
    occupancyFormat: 'अधिभोग',
    // QR Check-in
    scanQRCode: 'QR कोड स्कॅन करा',
    scanAtEntryPoints: 'प्रवेश बिंदूंवर कोणताही QR कोड स्कॅन करा',
    entryPoint: 'प्रवेश बिंदू',
    entryPointName: 'प्रवेश बिंदूचे नाव',
    enterEntryPointName: 'प्रवेश बिंदूचे नाव प्रविष्ट करा',
    groupRegistration: 'गट नोंदणी',
    groupSize: 'गटाचा आकार',
    groupSizePlaceholder: 'गटाचा आकार (1-50)',
    luggageCount: 'सामानाची संख्या',
    bagsLimit: 'बॅग मर्यादा (0-20)',
    intendedDestination: 'गंतव्य स्थान',
    customDestination: 'कस्टम गंतव्य',
    enterDestinationName: 'गंतव्याचे नाव प्रविष्ट करा',
    contactInformation: 'संपर्क माहिती',
    phoneNumberRequired: 'फोन नंबर *',
    enterPhoneNumber: 'फोन नंबर प्रविष्ट करा',
    contactNameOptional: 'संपर्क नाव (पर्यायी)',
    enterContactName: 'संपर्क नाव प्रविष्ट करा',
    groupSelfie: 'गट सेल्फी',
    takeGroupSelfie: 'गट सेल्फी घ्या',
    captureGroupPhoto: 'ओळखीसाठी गट फोटो कॅप्चर करा',
    completeRegistration: 'नोंदणी पूर्ण करा',
    qrCodeScanned: 'QR कोड स्कॅन झाला',
    qrScannedSuccessfully: 'QR यशस्वीरित्या स्कॅन झाला',
    qrCodeRequired: 'QR कोड आवश्यक',
    pleaseScanQRFirst: 'कृपया प्रथम QR कोड स्कॅन करा',
    selfieRequired: 'सेल्फी आवश्यक',
    pleaseTakeGroupSelfie: 'कृपया गट सेल्फी घ्या',
    invalidGroupSize: 'अवैध गट आकार',
    enterValidGroupSize: 'कृपया वैध गट आकार प्रविष्ट करा (1-50)',
    invalidLuggageCount: 'अवैध सामान संख्या',
    enterValidLuggageCount: 'कृपया वैध सामान संख्या प्रविष्ट करा',
    contactRequired: 'संपर्क आवश्यक',
    pleaseEnterContactPhone: 'कृपया संपर्क फोन नंबर प्रविष्ट करा',
    destinationRequired: 'गंतव्य आवश्यक',
    pleaseEnterCustomDestination: 'कृपया कस्टम गंतव्य प्रविष्ट करा',
    registrationComplete: 'नोंदणी पूर्ण',
    registrationSubmittedSuccess: 'तुमची गट नोंदणी यशस्वीरित्या सबमिट झाली!',
    registrationFailed: 'नोंदणी अयशस्वी',
    cameraAccess: 'कॅमेरा प्रवेश',
    cameraAccessMessage: 'QR कोड स्कॅन करण्यासाठी आम्हाला तुमच्या कॅमऱ्याची गरज आहे.',
    cameraDisabled: 'कॅमेरा प्रवेश अक्षम आहे.',
    enableInSettings: 'QR स्कॅन करण्यासाठी सेटिंग्जमध्ये सक्षम करा.',
    openSettings: 'सेटिंग्ज उघडा',
    scanAnyQRCode: 'कोणताही QR कोड स्कॅन करा',
    alignQRInFrame: 'QR कोड फ्रेममध्ये संरेखित करा',
    railwayStation: 'रेल्वे स्टेशन',
    busStand: 'बस स्टॅंड',
    parkingArea: 'पार्किंग क्षेत्र',
    other: 'इतर',
    // Lost & Found
    chooseOption: 'एक पर्याय निवडा',
    lost: 'हरवले',
    found: 'सापडले',
    addLostDetails: 'हरवलेले तपशील जोडा',
    addFoundDetails: 'सापडलेले तपशील जोडा',
    whatIsLost: 'काय हरवले?',
    whatIsFound: 'काय सापडले?',
    whereLost: 'कुठे हरवले',
    whereFound: 'कुठे सापडले',
    dateAndTime: 'तारीख आणि वेळ',
    selectDate: 'तारीख निवडा',
    selectTime: 'वेळ निवडा',
    contactPhoneRequired: 'संपर्क फोन *',
    yourContactPhone: 'तुमचा संपर्क फोन नंबर',
    photos: 'फोटो',
    submitLostReport: 'हरवलेली अहवाल सबमिट करा',
    submitFoundReport: 'सापडलेली अहवाल सबमिट करा',
    searchLostReports: 'हरवलेल्या अहवाल शोधा...',
    searchFoundReports: 'सापडलेल्या अहवाल शोधा...',
    recentLostReports: 'अलीकडील हरवलेल्या अहवाल',
    recentFoundReports: 'अलीकडील सापडलेल्या अहवाल',
    searchResults: 'शोध परिणाम',
    loadingReports: 'अहवाल लोड होत आहेत...',
    noLostReportsYet: 'अद्याप कोणतीही हरवलेली अहवाल नाही.',
    noFoundReportsYet: 'अद्याप कोणतीही सापडलेली अहवाल नाही.',
    beFirstToSubmit: 'प्रथम सबमिट करणारे व्हा!',
    pleaseFillRequired: 'कृपया आवश्यक फील्ड भरा',
    lostReportSubmitted: 'हरवलेली अहवाल यशस्वीरित्या सबमिट झाली.',
    foundReportSubmitted: 'सापडलेली अहवाल यशस्वीरित्या सबमिट झाली.',
    submissionFailed: 'सबमिट करण्यात अयशस्वी',
    failedToSubmitReport: 'अहवाल सबमिट करण्यात अयशस्वी',
    navigationNotAvailable: 'नेव्हिगेशन उपलब्ध नाही. कृपया पुन्हा प्रयत्न करा.',
    egWalletPerson: 'उदा., पाकीट, व्यक्तीचे नाव',
    egBagIdCard: 'उदा., बॅग, आयडी कार्ड',
    description: 'वर्णन',
    contactPhone: 'संपर्क फोन',
    shortDescription: 'संक्षिप्त वर्णन',
    locationOrLandmark: 'स्थान किंवा लँडमार्क',
    reportDetails: 'अहवाल तपशील',
    noReportData: 'अहवाल डेटा उपलब्ध नाही',
    lostItem: 'हरवलेले आयटम',
    foundItem: 'सापडलेले आयटम',
    status: 'स्थिती',
    itemInformation: 'आयटम माहिती',
    itemName: 'आयटमचे नाव',
    type: 'प्रकार',
    person: 'व्यक्ती',
    location: 'स्थान',
    address: 'पत्ता',
    coordinates: 'निर्देशांक',
    phone: 'फोन',
    email: 'ईमेल',
    reportInformation: 'अहवाल माहिती',
    reportedOn: 'अहवाल तारीख',
    reportedBy: 'अहवाल केले',
    user: 'वापरकर्ता',
    unknownItem: 'अज्ञात आयटम',
    noDescription: 'वर्णन नाही',
    recently: 'अलीकडे',
    justNow: 'आत्ताच',
    minutesAgo: 'मिनिटांपूर्वी',
    hoursAgo: 'तासांपूर्वी',
    daysAgo: 'दिवसांपूर्वी',
    noPhoneNumber: 'फोन नंबर नाही',
    contactNotAvailable: 'संपर्क फोन नंबर उपलब्ध नाही',
    unableToCall: 'फोन कॉल करू शकत नाही',
    unableToSendSMS: 'SMS पाठवू शकत नाही',
    call: 'कॉल करा',
    sendSMS: 'SMS पाठवा',
  },
};

/**
 * Get translation for current language
 */
export const getTranslation = async (key) => {
  const language = await getLanguage();
  const lang = language || LANGUAGES.ENGLISH;
  return translations[lang]?.[key] || translations[LANGUAGES.ENGLISH][key] || key;
};

/**
 * Get all translations for current language (synchronous version using stored language)
 */
export const getTranslations = async () => {
  const language = await getLanguage();
  const lang = language || LANGUAGES.ENGLISH;
  return translations[lang] || translations[LANGUAGES.ENGLISH];
};

