import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#FFF7ED'},
  fullscreenCenter: {flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24},
  splashLogoWrap: {width: 128, height: 128, marginBottom: 16},
  splashHalo: {position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'white', opacity: 0.2, borderRadius: 64},
  splashInner: {position: 'absolute', top: 16, right: 16, bottom: 16, left: 16, borderRadius: 56, alignItems: 'center', justifyContent: 'center'},
  splashEmoji: {fontSize: 40, color: 'white'},
  splashTitle: {fontSize: 40, color: 'white', fontWeight: '700', marginBottom: 4},
  splashSubtitle: {fontSize: 18, color: '#FEF3C7', marginBottom: 16},
  splashImage: {width: '100%', height: 120, borderRadius: 16, marginBottom: 16, opacity: 0.85},
  dotsRow: {flexDirection: 'row', gap: 6, marginBottom: 8},
  dot: {width: 8, height: 8, borderRadius: 4, backgroundColor: '#FDE68A'},
  splashFootnote: {color: '#FDE68A', fontSize: 12},

  homeContainer: {padding: 16, paddingBottom: 120},
  card: {backgroundColor: 'rgba(255,255,255,0.75)', borderRadius: 24, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: 'rgba(251,146,60,0.25)'},
  cardTall: {backgroundColor: 'rgba(255,255,255,0.75)', borderRadius: 24, padding: 16, marginBottom: 16, height: 240, borderWidth: 1, borderColor: 'rgba(251,146,60,0.25)'},
  cardCenter: {backgroundColor: 'rgba(255,255,255,0.75)', borderRadius: 24, padding: 16, marginBottom: 16, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(251,146,60,0.25)'},
  chatBox: {backgroundColor: 'rgba(255,255,255,0.92)', borderRadius: 24, padding: 12, marginBottom: 16, height: 420, borderWidth: 1, borderColor: 'rgba(251,146,60,0.25)', shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 8, shadowOffset: {width: 0, height: 4}, elevation: 2, overflow: 'hidden'},
  cardRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  cardRowJustify: {backgroundColor: 'rgba(255,255,255,0.75)', borderRadius: 24, padding: 16, marginBottom: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  mapImage: {position: 'absolute', top: 16, right: 16, bottom: 16, left: 16, borderRadius: 16},

  brandBadge: {width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', marginRight: 12},
  brandEmoji: {fontSize: 22, color: 'white'},
  brandTitle: {fontSize: 22, fontWeight: '800', color: '#7C2D12'},
  brandSubtitle: {fontSize: 13, color: '#9A3412'},
  headerActions: {flexDirection: 'row', gap: 8},

  sectionTitle: {fontSize: 18, fontWeight: '700', color: '#7C2D12', marginBottom: 8},
  sectionTitleAlt: {fontSize: 16, fontWeight: '700', color: '#FED7AA', marginBottom: 8},

  grid: {flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'space-between'},
  tile: {width: '48%', backgroundColor: 'rgba(255,255,255,0.9)', padding: 12, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(251,146,60,0.25)', alignItems: 'center'},
  tileBadge: {width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 6},
  tileEmoji: {fontSize: 18, color: 'white'},
  tileTitle: {fontSize: 12, fontWeight: '700', color: '#7C2D12', textAlign: 'center'},
  tileSubtitle: {fontSize: 10, color: '#9A3412', textAlign: 'center', marginTop: 2},

  bigRoundBtn: {width: 140, height: 140, borderRadius: 70, alignItems: 'center', justifyContent: 'center'},
  bigRoundText: {color: 'white', fontWeight: '800', fontSize: 36},
  smallMuted: {textAlign: 'center', color: '#9F1239'},
  smallMutedCenter: {textAlign: 'center', color: '#9A3412', marginTop: 8},
  sosWrap: {alignItems: 'center', marginTop: 12, marginBottom: 8},

  // Form rows
  fieldWrap: {flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 10},
  fieldLabel: {flexBasis: '40%', color: '#7C2D12', fontWeight: '700'},
  fieldInput: {flex: 1, height: 44, borderRadius: 12, paddingHorizontal: 12, backgroundColor: 'rgba(255,153,51,0.08)', borderWidth: 1, borderColor: '#FDBA74', justifyContent: 'center'},

  headerWrap: {backgroundColor: 'rgba(255,255,255,0.75)', borderRadius: 24, padding: 12, marginBottom: 16, borderWidth: 1, borderColor: 'rgba(251,146,60,0.25)'},
  headerRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  headerBtn: {width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,153,51,0.15)', alignItems: 'center', justifyContent: 'center'},
  headerBtnEmoji: {fontSize: 18},
  headerTitle: {fontSize: 18, fontWeight: '800'},
  headerBadge: {width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center'},
  headerBadgeEmoji: {color: 'white'},

  textOrange: {color: '#9A3412'},
  textOrangeStrong: {color: '#7C2D12', fontWeight: '800'},
  textRed: {color: '#FCA5A5'},
  textRedStrong: {color: '#991B1B', fontWeight: '800'},
  textRedMuted: {color: '#EF4444'},

  screenPad: {padding: 16, paddingBottom: 120},

  listRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: 'rgba(255,255,255,0.8)', borderRadius: 16, padding: 12, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(251,146,60,0.25)'},
  rowTitle: {fontSize: 14, fontWeight: '700', color: '#7C2D12'},
  rowSubtitle: {fontSize: 12, color: '#9A3412'},
  cardTitle: {fontSize: 16, fontWeight: '700', color: '#7C2D12'},
  ctaBtn: {marginTop: 12, backgroundColor: '#DC2626', borderRadius: 24, paddingVertical: 12, paddingHorizontal: 16},
  ctaText: {color: 'white', fontWeight: '700'},
  primaryBtn: {marginTop: 8, backgroundColor: '#FB923C', borderRadius: 24, paddingVertical: 14, alignItems: 'center'},
  primaryBtnText: {color: 'white', fontWeight: '700', fontSize: 16},

  actionRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 12, borderWidth: 1, borderRadius: 16, marginBottom: 10},
  smallBtn: {borderRadius: 16, paddingHorizontal: 12, paddingVertical: 6},
  smallBtnText: {color: 'white', fontWeight: '700', fontSize: 12},
  kvRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 6},
  kvLabel: {color: '#FECACA'},
  kvValue: {color: '#FEE2E2', fontFamily: 'monospace'},
  kvLabelDark: {color: '#7C2D12'},
  kvValueDark: {color: '#7C2D12', fontWeight: '700'},

  rowBadgeLine: {flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6},
  okText: {color: '#15803D', fontWeight: '600'},

  matchRow: {flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 8},
  heatImage: {marginTop: 8, height: 160, borderRadius: 12},
  statCard: {flexBasis: '48%', backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 16, padding: 12, borderWidth: 1, alignItems: 'center'},
  statValue: {fontSize: 22, fontWeight: '800', marginTop: 8},
  statLabel: {fontSize: 12, color: '#FED7AA'},

  bottomBar: {position: 'absolute', left: 0, right: 0, bottom: 0, padding: 4, backgroundColor: 'transparent'},
  bottomBarInner: {flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.95)', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingVertical: 6, paddingHorizontal: 4, borderWidth: 1, borderColor: 'rgba(251,146,60,0.2)', shadowColor: '#000', shadowOpacity: 0.05, shadowOffset: {width: 0, height: -2}, shadowRadius: 4, elevation: 3},
  navItem: {alignItems: 'center', paddingHorizontal: 6, flex: 1},
  navIcon: {width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.6)'},
  navIconActive: {backgroundColor: '#FB923C'},
  navIconEmoji: {fontSize: 18},
  navIconEmojiActive: {},
  navLabel: {fontSize: 9, color: '#9A3412', marginTop: 2, fontWeight: '500'},
  navLabelActive: {color: '#FB923C', fontWeight: '700'},

  round32: {width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center'},
  round32Text: {color: 'white'},
  round40: {width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center'},
  round40Text: {color: 'white'},
  round48: {width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center'},
  round48Text: {color: 'white'},
  round64: {width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center'},
  round64Light: {width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,153,51,0.15)'},
  round64Text: {color: 'white', fontSize: 20},

  qrCam: {height: 200, borderRadius: 16, backgroundColor: 'black', overflow: 'hidden', alignItems: 'center', justifyContent: 'center'},
  qrCamInner: {width: 192, height: 192, borderRadius: 16, alignItems: 'center', justifyContent: 'center'},
  qrHint: {position: 'absolute', bottom: 8, color: '#FDE68A', fontSize: 12},

  selfieBox: {height: 180, borderRadius: 16, borderWidth: 2, borderStyle: 'dashed', borderColor: '#FDBA74', alignItems: 'center', justifyContent: 'center'},

  searchRow: {flexDirection: 'row', alignItems: 'center', gap: 8},
  searchInput: {flex: 1, height: 44, borderBottomWidth: 2, borderBottomColor: '#FDBA74', justifyContent: 'center'},
  placeholder: {color: '#9A3412'},
  inputRow: {flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 16, padding: 8, borderWidth: 1, borderColor: 'rgba(251,146,60,0.25)'},

  msgRowBot: {flexDirection: 'row', alignItems: 'flex-start', gap: 8},
  msgBubbleBot: {backgroundColor: 'rgba(255,255,255,0.85)', borderRadius: 16, padding: 10, maxWidth: '75%'},
  msgTextBot: {color: '#7C2D12', fontSize: 13},
  msgRowUser: {flexDirection: 'row', alignItems: 'flex-start', gap: 8, justifyContent: 'flex-end'},
  msgBubbleUser: {backgroundColor: '#FB923C', borderRadius: 16, padding: 10, maxWidth: '75%'},
  msgTextUser: {color: 'white', fontSize: 13},
  chipsRow: {flexDirection: 'row', gap: 8, marginBottom: 12},
  chip: {paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, backgroundColor: 'rgba(255,153,51,0.12)'},
  chipActive: {backgroundColor: '#FB923C'},
  chipText: {fontSize: 12, color: '#9A3412'},
  chipTextActive: {fontSize: 12, color: 'white', fontWeight: '700'},
  quickTitle: {fontSize: 13, fontWeight: '700', color: '#7C2D12', marginBottom: 8},
  quickChips: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},

  sosPulseWrap: {alignItems: 'center', justifyContent: 'center', height: 260, marginBottom: 16},
  sosPulse: {position: 'absolute', width: 220, height: 220, borderRadius: 110, backgroundColor: '#EF4444'},
  sosBtn: {width: 160, height: 160, borderRadius: 80, alignItems: 'center', justifyContent: 'center'},
  sosBtnText: {color: 'white', fontSize: 40, fontWeight: '800'},
  sosNote: {color: '#FEE2E2', textAlign: 'center', marginTop: 12, fontSize: 14},
  sosSubNote: {color: '#FCA5A5', textAlign: 'center', marginTop: 4, marginBottom: 16, fontSize: 13},
  textCenter: {alignItems: 'center'},

  // Dark card text variants (for SOS screen)
  rowTitleAlt: {fontSize: 14, fontWeight: '700', color: '#FDE68A'},
  rowSubtitleAlt: {fontSize: 12, color: '#F59E0B'},

  // Auth/Login
  authContainer: {padding: 16, paddingBottom: 120},
  authTitle: {fontSize: 22, fontWeight: '800', color: '#7C2D12', textAlign: 'center', marginBottom: 12},
  inputWrap: {backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 16, padding: 12, borderWidth: 1, borderColor: 'rgba(251,146,60,0.25)', marginBottom: 12},
  inputLabel: {fontSize: 12, color: '#9A3412', marginBottom: 6, fontWeight: '700'},
  textInput: {height: 44, borderRadius: 12, paddingHorizontal: 12, backgroundColor: 'rgba(255,153,51,0.08)', color: '#7C2D12', borderWidth: 1, borderColor: '#FDBA74'},
  linkText: {color: '#FB923C', fontWeight: '700'},
});

